# Generated by Django 5.2 on 2025-04-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_email', models.EmailField(max_length=254, unique=True)),
                ('emp_phn_no', models.CharField(max_length=15)),
                ('emp_address', models.TextField()),
                ('emp_salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
