# Generated by Django 5.2 on 2025-05-01 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0002_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
